### PR TITLE
Upgrade Kafka version to 3.4

### LINKED ISSUE #1960: Add support for Kafka version 3.4
This PR adds support for the future Kafka 3.4.0 release

Action items:
- check Kafka 3.4 compatibility with the current Cruise Control state
- update required parts
- test compatibility again

### PR DESCRIPTION
**Pull request by egyedt**
This PR resolves #1960.

### CODE REVIEW

**Comment by egyedt** [comment]
@efeg, @CCisGG, @viktorsomogyi 
Could you please review this small upgrade?

**Comment by CCisGG** [comment]
Hi @egyedt , thank you for taking care of this! 

The reason we keep kafka-version at 3.1* is LinkedIn is still using kafka 3.0 ~ 3.1. We anticipate we'll stay on that version for at least another few months. Please feel free to update the kafka dependency version on your fork of CC, but we'll keep the version as what it is for now in open source CC.

**Comment by erikgb** [comment]
@CCisGG Can we upgrade the Kafka client used by cruise-control now? Or do we need to fork the project? I would expect the clients to be backwards compatible. Forward compatible is a bit more tricky. We want to connect to our clusters using PEM certificates avoiding the pesky keystores (with passwrods). That requires a newer client version.

**Comment by CCisGG** [comment]
> @CCisGG Can we upgrade the Kafka client used by cruise-control now? Or do we need to fork the project? I would expect the clients to be backward compatible. Forward compatible can be a bit more tricky. We want to connect to our clusters using PEM certificates avoiding the pesky keystores (with passwords). That requires a newer client version.

Hi @erikgb , thanks for bringing this up. Could you please elaborate  a bit more on the "We want to connect to our clusters using PEM certificates avoiding the pesky keystores (with passwords). That requires a newer client version."? Do you mean that using current CC code cannot connect your CC instance to your kafka cluster?

**Comment by erikgb** [comment]
@CCisGG We run CC on Kubernetes, and have automation to issue certificates used to authenticate to our external clusters. This automation is migrating away from legacy keystores/truststores (both JKS and PKCS#12) to pure PEM format with unencrypted private keys. The current Kafka client used in CC does not allow for this, as it doesn't include https://issues.apache.org/jira/browse/KAFKA-12703. To use unencrypted private keys with PEM, the Kafka client version must be at least 3.3.0.

**Comment by viktorsomogyi** [comment]
@egyedt the project already supports 3.5.1 as of now. Would you please consider closing this ticket?

**Comment by egyedt** [comment]
The project supports 3.5.1 now, and this PR is not needed anymore.

**Pull request closed without merging**
