### PR TITLE
fix: Fix CVEs

### LINKED ISSUE #2219: Update Dependencies to Address CVEs
### Issue description

This issue is to track the update of dependencies to address known CVEs in the following packages. Upgrading these dependencies ensures improved security and resolves any vulnerabilities that might affect the project.

Packages and CVEs

### Zookeeper

Current Version: 3.8.3
Upgrade to: 3.9.3

### Netty

Current Version: 4.1.100.Final
Upgrade to: 4.1.114.Final

### Jetty

Current Version: 9.4.53.v20231009
Upgrade to: 9.4.56.v20240826

### Nimbus JOSE+JWT

Current Version: 9.24
Upgrade to: 9.45

Upgrade the versions of the above packages to the latest versions as specified to mitigate security risks.

### PR DESCRIPTION
**Pull request by aswinayyolath**
## Summary

Update dependencies to fix CVEs: Zookeeper, Netty, Jetty, Nimbus JOSE+JWT

## Categorization
- [x] security/CVE

This PR resolves #2219

### CODE REVIEW

**Comment by aswinayyolath** [comment]
I tried running tests and it Passed

image

@CCisGG @akatona84 could you pls review?

**Review by akatona84 — APPROVED** [review]
lgtm, thx.
there's another PR which addresses part of these: #2141 , but it is not updated with the latest versions yet.

**Comment by aswinayyolath** [comment]
Thanks for approving the changes. Merging this will resolve some of the CVEs and eliminate them from the scans.

**Comment by CCisGG** [comment]
Running internal checks and will merge once it passes.

**Comment by aswinayyolath** [comment]
> Running internal checks and will merge once it passes.

Thanks

**Comment by slaupster** [comment]
🙇

**Comment by CCisGG** [comment]
Hi @aswinayyolath @akatona84 , fyi we had to revert this PR in the migrate_to_kafka_3_0 branch (not in main branch), because this is causing some ZK related issue for us. It might be related to this one: https://issues.apache.org/jira/browse/ZOOKEEPER-4888

I'm not sure if you have tested this version with ZK. Just in case anyone see this comment and see similar issues, please tag me and I'll revert the PR in main branch.

This is the stacktrace:

```
2025/04/01 04:24:25.117 WARN [ClientCnxn] [main-SendThread] [kafka-cruise-control] [] Session 0x0 for server XXX, Closing socket connection. Attempting reconnect except it is a SessionExpiredException or SessionTimeoutException.
org.apache.zookeeper.ClientCnxn$EndOfStreamException: channel for sessionid 0x0 is lost
        at org.apache.zookeeper.ClientCnxnSocketNetty.doTransport(ClientCnxnSocketNetty.java:287) ~[org.apache.zookeeper.zookeeper-3.9.3.jar:3.9.3]
        at ...

2025/04/01 03:43:44.391 ERROR [ClientCnxnSocketNetty] [zkNetty-EpollEventLoopGroup-2-1] [kafka-cruise-control] [] Unexpected throwable io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version 
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:500) ~[io.netty.netty-codec-4.1.114.Final.jar:4.1.114.Final]
...
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: protocol_version at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?] at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?] at sun.security.ssl.TransportContext.fatal(TransportContext.java:358) ~[?:?] at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) ~[?:?]

...

2025/04/01 03:43:44.398 ERROR [KafkaCruiseControlUtils] [main] [kafka-cruise-control] [] Unable to find apply method in KafkaZkClient for Kafka 3.1+.
java.lang.reflect.InvocationTargetException: null
...
Caused by: kafka.zookeeper.ZooKeeperClientTimeoutException: Timed out waiting for connection while in state: CONNECTING
```

**Pull request merged**
