### PR TITLE
Adding support for Reason parameter to admin, stop_proposal_execution…

### LINKED ISSUE #1554: Support for reason parameter in GET and admin POST requests
As of today, reason parameter is supported by the following POST endpoints:
- pause_sampling
- resume_sampling
- add_broker
- demote_broker
- fix_offline_replicas
- rebalance
- remove_broker
- review
- topic_configuration

So currently, this parameter is missing from all GET endpoints and the following POST endpoints:
- admin
- stop_proposal_execution

Adding the parameter to the remaining requests will provide a robust way to audit all requests handled by CC

### PR DESCRIPTION
**Pull request by girijasameera**
… and GET endpoints

This PR resolves #1554

### CODE REVIEW

**Comment by girijasameera** [comment]
@efeg Would you be the right person to ask for a review? I've followed the other endpoints mentioned in the issue that already have the reason parameter, please let me know if i have missed anything.

**Review by zornhsu — APPROVED** [review]
LGTM. Thanks for the patch, @girijasameera!
Would you mind also adding these parameters to
1. `rightsize.yaml`
2. respective tables in `docs/wiki/User Guide/REST-APIs.md`?

**Comment by girijasameera** [comment]
Will do, @zornhsu. Thanks for the review. Please give me a day or two.

**Comment by girijasameera** [comment]
@zornhsu I've made the changes you asked for, please take a look.

**Review by zornhsu — APPROVED** [review]
LGTM. Thanks for the update, @girijasameera!

**Pull request merged**
