### PR TITLE
Fix the problem that the lack of available brokers causes the cc startup to fail

### PR DESCRIPTION
**Pull request by wenbingshen**
This PR resolves [1535](https://github.com/linkedin/cruise-control/issues/1535).

When creating a sample topic, we should first determine whether the topic exists, otherwise the error reported by [1535](https://github.com/linkedin/cruise-control/issues/1535) will occur.

### CODE REVIEW

**Comment by zornhsu** [comment]
Thanks for the patch, Wenbing! Can you reply to my comment on the linked issue?

**Review by zornhsu — COMMENTED** [review]
Thanks for the patch, Wenbing! Can you reply to my comment on the [linked issue](https://github.com/linkedin/cruise-control/issues/1535)?

**Comment by wenbingshen** [comment]
> Thanks for the patch, Wenbing! Can you reply to my comment on the [linked issue](https://github.com/linkedin/cruise-control/issues/1535)?

@zornhsu Thank you for your reminder, I am closing this pr now.

**Comment by zornhsu** [comment]
We encourage users to upgrade Kafka if possible. Alternatively, users can cherry-pick [KAFKA-8875](https://issues.apache.org/jira/browse/KAFKA-8875) to their Kafka branch. 

I have #1555 pending to enhance CC documentation. @wenbingshen, would you mind creating another PR to add more details in the [Troubleshooting](https://github.com/linkedin/cruise-control/wiki/Troubleshooting) page?

**Pull request closed without merging**
