### PR TITLE
Update Netty dependency to 4.1.89.Final (#1969)

### LINKED ISSUE #1969: Update Netty dependency to 4.1.89.Final
Currently used version of Netty got CVE. Could it be bumped to latest: 4.1.89.Final ?

### PR DESCRIPTION
**Pull request by mrlogan**
This PR resolves #1969 .

### CODE REVIEW

**Review by CCisGG — APPROVED** [review]
LGTM. Thanks!

**Comment by CCisGG** [comment]
Hi @mrlogan, I'll have to revert it since it's blocking our internal build with a weird issue:

```
 * What went wrong:
Execution failed for task ':likafka-cruise-control:likafka-cruise-control-impl_2.12:createCmptDefMain'.
> Could not resolve all files for configuration ':likafka-cruise-control:likafka-cruise-control-impl_2.12:filteredCmptDefCompileClasspathMain'.
   > Could not find netty-transport-native-epoll-4.1.89.Final-linux-x86_64.jar (io.netty:netty-transport-native-epoll:4.1.89.Final).
```

Somehow it searches for netty-transport-native-epoll-4.1.89.Final-linux-x86_64 instead of netty-transport-native-epoll-4.1.89.Final, and fail the build. Do you happen to know why that happens?

**Comment by CCisGG** [comment]
Reverted: https://github.com/linkedin/cruise-control/pull/1984

We'd appreciate if you could provide any insights on the issue. Meanwhile we will keep investigating why that happens. Once the issue is resolved, we will re-apply this change.

**Comment by mrlogan** [comment]
@CCisGG Hi, interesting. What machine are you building it on? Is it Apple with M1? I had found this entry on SO https://stackoverflow.com/questions/72664676/what-have-caused-the-problem-of-could-not-find-netty-transport-native-epoll-4-1?rq=1   and those https://stackoverflow.com/questions/72847122/missing-osx-aarch-64-classifier-version-for-netty-transport-native-epoll   and https://github.com/netty/netty/issues/12024, Unfortunately doesn;t have M1 to play with :(

**Comment by CCisGG** [comment]
@mrlogan Hi, I'm using a mac intel machine. Thanks for providing the references! I'll take a shot.

**Comment by mrlogan** [comment]
Awesome. Thank you very much for that :)

wt., 28 mar 2023 o 22:39 Hao Geng ***@***.***> napisał(a):

**Pull request merged**
