### PR TITLE
Update ReplicationThrottleHelper to use AdminClient

### PR DESCRIPTION
**Pull request by mimaison**
This removes the dependency on ZooKeeper of this component.

After this, the last place Cruise Control requires ZooKeeper is `BrokerFailureDetector`. Unfortunately in KRaft mode, Kafka does not have a way to listen for broker changes. I can think of a couple of workarounds but has this been discussed already?

### CODE REVIEW

**Comment by mimaison** [comment]
@efeg Did you get a chance to take a look? Thanks

**Review by efeg — APPROVED** [review]
@mimaison Thanks for the PR -- sorry for the delay in reviewing it!
LGTM.

**Comment by mimaison** [comment]
Thanks @efeg !
Can you answer my question above regarding `BrokerFailureDetector`?

**Comment by efeg** [comment]
@mimaison That is a good question and a valid point. We haven't had a discussion regarding the migration plan for `BrokerFailureDetector` off of ZooKeeper. I would be happy to discuss further if you have some proposals on it -- maybe we can discuss this under a relevant GitHub issue.

**Pull request merged**
